feat: change from png to svg
Diabol/delivery-pipeline-plugin pull request #346
Opened 2023-01-07 00:51 UTC by emanuelflp

As Jenkins move to use SVG as default in your internal images, this PR adjusts to use it. See [Here](https://issues.jenkins.io/browse/JENKINS-68249)

Resolves this [Issue](https://issues.jenkins.io/browse/JENKINS-68812)

2023-01-24 09:00 UTC, craigwebb-xft approved these changes

2023-04-12 04:35 UTC, m-hruby approved these changes

2023-05-29 12:26 UTC, RHeynsZa approved these changes

2023-08-23 05:50 UTC, ibmboy19 commented
Anyone to approve and merge this?

2023-09-21 13:05 UTC, hellemansjelle requested changes

2023-09-21 13:05 UTC, hellemansjelle commented on src/main/webapp/pipe.js
> +        html.push('<img class="icon-clock icon-md" title="Build now" src="' + resURL + '/images/24x24/clock.svg">');
I think this should be '/images/svgs/clock.svg'

2024-03-06 16:37 UTC, piotrwach commented
The same issue has been fixed here: https://github.com/Diabol/delivery-pipeline-plugin/pull/347

just fyi, we are also affected by this, and we would appreciate if this fix lands in the next plugin version if possible :)

2026-02-23 20:31 UTC, closed without merging